language: node_js
node_js:
  - "4"

before_install:
  - "if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi"

script:
  - "npm test"
  - "npm run build"

addons:
  artifacts:
    s3_region: ap-northeast-1
    paths: ./build/image-lambda.zip